'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://looVF.org/", ConfigurationName:="ServiceReference1.looVFSoap")>  _
    Public Interface looVFSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaSuccessivoMultimedia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaSuccessivoMultimedia(ByVal idTipologia As String, ByVal Categoria As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaCategorie", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaCategorie() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaQuantiFiles", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaQuantiFiles(ByVal idTipologia As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaMultimediaDaId", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaMultimediaDaId(ByVal Tipologia As String, ByVal idMultimedia As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaImmaginiPerGriglia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaImmaginiPerGriglia(ByVal QuanteImm As String, ByVal Categoria As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/RitornaFiles", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RitornaFiles() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://looVF.org/TornaNumeroImmaginePerSfondo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TornaNumeroImmaginePerSfondo() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface looVFSoapChannel
        Inherits ServiceReference1.looVFSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class looVFSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.looVFSoap)
        Implements ServiceReference1.looVFSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RitornaSuccessivoMultimedia(ByVal idTipologia As String, ByVal Categoria As String) As String Implements ServiceReference1.looVFSoap.RitornaSuccessivoMultimedia
            Return MyBase.Channel.RitornaSuccessivoMultimedia(idTipologia, Categoria)
        End Function
        
        Public Function RitornaCategorie() As String Implements ServiceReference1.looVFSoap.RitornaCategorie
            Return MyBase.Channel.RitornaCategorie
        End Function
        
        Public Function RitornaQuantiFiles(ByVal idTipologia As String) As String Implements ServiceReference1.looVFSoap.RitornaQuantiFiles
            Return MyBase.Channel.RitornaQuantiFiles(idTipologia)
        End Function
        
        Public Function RitornaMultimediaDaId(ByVal Tipologia As String, ByVal idMultimedia As String) As String Implements ServiceReference1.looVFSoap.RitornaMultimediaDaId
            Return MyBase.Channel.RitornaMultimediaDaId(Tipologia, idMultimedia)
        End Function
        
        Public Function RitornaImmaginiPerGriglia(ByVal QuanteImm As String, ByVal Categoria As String) As String Implements ServiceReference1.looVFSoap.RitornaImmaginiPerGriglia
            Return MyBase.Channel.RitornaImmaginiPerGriglia(QuanteImm, Categoria)
        End Function
        
        Public Function RitornaFiles() As String Implements ServiceReference1.looVFSoap.RitornaFiles
            Return MyBase.Channel.RitornaFiles
        End Function
        
        Public Function TornaNumeroImmaginePerSfondo() As String Implements ServiceReference1.looVFSoap.TornaNumeroImmaginePerSfondo
            Return MyBase.Channel.TornaNumeroImmaginePerSfondo
        End Function
    End Class
End Namespace
